# yamllint disable rule:line-length

name: Test

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        exclude:
          - os: macos-latest
            python-version: '3.6'
          - os: macos-latest
            python-version: '3.7'
          - os: macos-latest
            python-version: '3.8'
          - os: windows-latest
            python-version: '3.6'
          - os: windows-latest
            python-version: '3.7'
          - os: windows-latest
            python-version: '3.8'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test
        shell: bash
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          set -uexo pipefail
          pip install -e file:///$(pwd)#egg=autopxd2[dev]
          pytest

      - name: Test_Windows
        shell: powershell
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          pip install -e .[dev]
          pytest
